#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor HDMI-1 -d 1 2 3 4 5 &
# bspc monitor eDP-1 -d 6 7 8 9 0 
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#000000'
bspc config active_border_color '#00d7ff'
bspc config focused_border_color '#d7ff00'

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Alacritty state=floating follow=on
bspc rule -a Chromium desktop='^5' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Gpick state=floating follow=on center
bspc rule -a mplayer2 state=floating
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a qutebrowser desktop='^5' follow=on
bspc rule -a Surf desktop='^6' state=tiled follow=on
bspc rule -a Thunderbird desktop='^6' state=tiled follow=on
bspc rule -a Zotero state=tiled follow=on center
